Task_1_1_1
pelageech/nsujava pull request #4
Opened 2022-09-15 02:32 UTC by pelageech

2022-09-20 10:49 UTC, shadrina requested changes

2022-09-20 10:49 UTC, shadrina commented on Task_1_1_1/src/main/java/Heapsort.java
> + *                              and so on.
Ой прикольно

2022-09-20 10:49 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +
Странно, что линтер такое съел. После аннотации достаточно одного перевода строки.

2022-09-20 10:49 UTC, shadrina commented on Task_1_1_1/src/test/java/HeapsortTest.java
> +
Не хватает: 

- Тест с пустым массивом
- Тест с массивом из одного элемента
- Тест с массивом из случайных чисел. См. `java.util.Random`

2022-09-20 10:49 UTC, shadrina commented on Task_1_1_1/src/main/java/Heapsort.java
> +  public static List<Integer> heapsort(List<Integer> arr) {
Ты используешь список, а не массив. Поэтому `arr` -- не лучшее название для переменной типа `List<T>`.

2022-09-20 11:40 UTC, pelageech commented on Task_1_1_1/src/main/java/Heapsort.java
> +  public static List<Integer> heapsort(List<Integer> arr) {
Я правильно понял, что нужно `ArrayList<T>` использовать, или следует сменить название переменной?

2022-09-20 11:46 UTC, shadrina commented on Task_1_1_1/src/main/java/Heapsort.java
> +  public static List<Integer> heapsort(List<Integer> arr) {
Нет, просто поставь более подходящее название

2022-09-21 07:21 UTC, shadrina reviewed
В остальном ок

2022-09-21 07:21 UTC, shadrina commented on Task_1_1_1/script.bat
> +jar cf .\make\jar\Heapsort.jar -C .\make\bin .
Вот тут не хватает команды, которая этот jar исполнила бы (`java`)

2022-09-25 14:48 UTC, shadrina approved these changes
Сдано

2022-09-25 15:01 UTC, merged