Task_1_2_1
pelageech/nsujava pull request #6
Opened 2022-09-26 12:49 UTC by pelageech

2022-10-03 10:42 UTC, shadrina requested changes
Хороший аккуратный код. Доведи, пожалуйста, до красоты.

2022-10-03 10:42 UTC, shadrina commented on README.md
> -# nsujava
Изменение не относится ко второй задаче. Если хочется изменить README, делаем отдельную ветку, в ней меняем README, открываем PR и заливаем в мастер.

2022-10-03 10:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +  }
Это у тебя была эпопея с кол-вом пробелов?

2022-10-03 10:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +      capacity = capacity * 3 / 2;
А расскажи, почему выбран такой коэффициент.

2022-10-03 10:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +    arrayStack[size] = null;
А вот это обязательно делать?

2022-10-03 10:42 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +    }
Вместо вот этих танцев с бубном можно сделать `Arrays.copyOfRange`.
А если хочется совсем красиво, можно сделать приватный конструктор, который принимаем массив и сразу его копирует в стек.

2022-10-03 12:23 UTC, pelageech commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +      capacity = capacity * 3 / 2;
Нам на императивном программировании рассказывал Гатилов, что умножать лучше следует cap на 3/2, чтобы память не степенью 2, а 1.5 увеличивалась.

2022-10-03 12:27 UTC, pelageech commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +  }
проверка жаловалась на то, что отступов, мол, в 2 раза больше, чем надо. Я в intellij подкрутил, чтоб табом он 2 пробела ставил, а если внутри круглых скобок огромное выражение ставлю (в assertEquals, например), то нормальный таб из 4 пробелов

2022-10-03 12:43 UTC, pelageech commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +    arrayStack[size] = null;
Скорее всего нет, так как вытащенный из стека объект уже больше использоваться не будет, более того он может быть замещён новым объектом, поэтому сборщик мусора сам удалит то, что было в arrayStack[size]

2022-10-03 12:44 UTC, pelageech commented on README.md
> -# nsujava
Сам не понял, как это изменилось) но постараюсь делать как надо

2022-10-03 18:33 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +      capacity = capacity * 3 / 2;
Повезло вам с лектором

2022-10-05 06:09 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +    capacity = size * 3 / 2;
Дублируется коэффициент

2022-10-05 08:49 UTC, shadrina reviewed
reviewdog ругается

2022-10-05 08:50 UTC, shadrina reviewed
Ок, но надо варнинги починить

2022-10-05 08:50 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +  private static final float FACTOR_ARRAY_REALLOC = 1.5f;
Глянь плиз, куда принято тащить константы. Я обычно уношу наверх вообще все филды вне зависимости от их видимости (между собой, конечно, упорядочиваю).

2022-10-05 11:55 UTC, pelageech commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +  private static final float FACTOR_ARRAY_REALLOC = 1.5f;
да, не подумал) вынес на самый верх константу

2022-10-11 18:17 UTC, shadrina approved these changes

2022-10-11 18:17 UTC, shadrina commented on Task_1_2_1/src/main/java/ru/nsu/ablaginin/MyStack.java
> +             Arrays.asList(myStack.arrayStack).subList(0, size)
Дима догадался сделать еще красивее: `Arrays.equals(elements, 0, length, other.elements, 0, stack.length);`

2022-10-12 00:40 UTC, merged