Task_1_2_3
pelageech/nsujava pull request #8
Opened 2022-10-23 04:41 UTC by pelageech

2022-10-24 08:05 UTC, shadrina reviewed
Мельком посмотрела, это не ревью, просто комментарий.

> CI doesn't support records

Не в CI проблема. Gradle собирает проект определенной версией Java. Уточнить эту версию можно в `build.gradle`. Если уточнения нет, берется версия из $JAVA_HOME. А рекорды появились в 14.

С Колей выяснили, что надо добавить в билд-скрипт:

```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
```

Вместо 17 можешь указать любую версию 14-17.

2022-10-31 13:53 UTC, shadrina requested changes

2022-10-31 13:53 UTC, shadrina commented on Task_1_2_3/src/main/java/ru/nsu/ablaginin/Edge.java
> +record Edge<T extends Comparable<T>>(Vertex<T> from, Vertex<T> to, Integer weight) {
Мне кажется, тут теряются основные бенефиты от использования record вместо обычного класса

2022-10-31 13:53 UTC, shadrina commented on Task_1_2_3/src/main/java/ru/nsu/ablaginin/Graph.java
> +    edges = new HashMap<>();
Погугли, что такое init block в Java

2022-10-31 13:53 UTC, shadrina commented on Task_1_2_3/src/main/java/ru/nsu/ablaginin/Graph.java
> +  private final Map<T, Vertex<T>> vertexes;
Вроде vertices

2022-10-31 13:53 UTC, shadrina commented on Task_1_2_3/src/test/java/ru/nsu/ablaginin/EdgeTest.java
> +  void getWeight() {
Все-таки постфикс `Test` лучше не опускать

2022-10-31 13:53 UTC, shadrina commented on Task_1_2_3/src/test/java/ru/nsu/ablaginin/GraphTest.java
> +    File file = new File("src/test/resources/input_1.txt");
Твой проект превращается в исполняемый JAR. Этот JAR может быть исполнен где угодно в файловой системе. А здесь указан относительный путь => везде, кроме корня проекта, тут будет `FileNotFoundException`. Погугли, как правильно читать ресурсы с помощью `getResourceAsStream`

2022-10-31 14:07 UTC, pelageech commented on Task_1_2_3/src/main/java/ru/nsu/ablaginin/Graph.java
> +  private final Map<T, Vertex<T>> vertexes;
Эти формы равносильны [https://en.wikipedia.org/wiki/Vertex_(geometry)](url)

2022-10-31 14:13 UTC, pelageech commented on Task_1_2_3/src/main/java/ru/nsu/ablaginin/Graph.java
> +    edges = new HashMap<>();
А как быть с конструктором пустого графа? пустой блок оставить?

2022-10-31 14:43 UTC, pelageech commented on Task_1_2_3/src/main/java/ru/nsu/ablaginin/Edge.java
> +record Edge<T extends Comparable<T>>(Vertex<T> from, Vertex<T> to, Integer weight) {
А какие? IDE само мне рекомендует на record поменять, и из методов только геттеры нужны (оказывается, рекорд их сам создаёт)

2022-10-31 16:16 UTC, shadrina commented on Task_1_2_3/src/main/java/ru/nsu/ablaginin/Graph.java
> +    edges = new HashMap<>();
Да

2022-10-31 16:20 UTC, shadrina commented on Task_1_2_3/src/main/java/ru/nsu/ablaginin/Edge.java
> +record Edge<T extends Comparable<T>>(Vertex<T> from, Vertex<T> to, Integer weight) {
> и из методов только геттеры нужны

А остальные ты для корректности переопределил?

Если все, что генерируется автоматически, имеет использования, то ок. А сомнения появились, потому что многие доступные для генерации методы пришлось писать вручную.

2022-11-01 00:51 UTC, pelageech commented on Task_1_2_3/src/main/java/ru/nsu/ablaginin/Edge.java
> +record Edge<T extends Comparable<T>>(Vertex<T> from, Vertex<T> to, Integer weight) {
Только недавно сообразил, что геттеры не нужно писать благодаря рекорду. Поэтому уже почистил

2022-11-02 05:57 UTC, shadrina approved these changes
Сдано

2022-11-02 05:58 UTC, merged